package com.expertworks.lms.model;

import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.expertworks.lms.http.GroupDTO;
import com.expertworks.lms.http.PartnerDTO;

@DynamoDBTable(tableName = "Group")

public class Group implements Comparable<Group> {
	


	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String groupId;

	@DynamoDBRangeKey // CustomerBookmark Table referred.
	private String sk;

	@DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
	private Date createdDate;

	@DynamoDBAttribute
	private String name;
	
	@DynamoDBAttribute
	private String email;

	@DynamoDBAttribute
	private String teamId;

	@DynamoDBAttribute
	private String img;
	
	@DynamoDBAttribute
	private String partnerId;
	
	@DynamoDBAttribute
	private String region;
	
	@DynamoDBAttribute
	private String userLimit;

	public int compareTo(Group partner) {
		return sk.compareTo(partner.sk);
	}
	
	public GroupDTO toGroupDTO() {
		GroupDTO groupDTO = new GroupDTO();
		groupDTO.setTeamId(this.teamId);
		groupDTO.setSk(this.sk);
		groupDTO.setName(this.name);
		groupDTO.setEmail(this.email);
		groupDTO.setRegion(this.region);
		groupDTO.setUserLimit(this.userLimit);
		
		return groupDTO;
	}


	public String getGroupId() {
		return groupId;
	}


	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}


	public String getSk() {
		return sk;
	}


	public void setSk(String sk) {
		this.sk = sk;
	}


	public Date getCreatedDate() {
		return createdDate;
	}


	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public String getTeamId() {
		return teamId;
	}


	public void setTeamId(String teamId) {
		this.teamId = teamId;
	}


	public String getImg() {
		return img;
	}


	public void setImg(String img) {
		this.img = img;
	}

	public String getPartnerId() {
		return partnerId;
	}

	public void setPartnerId(String partnerId) {
		this.partnerId = partnerId;
	}

	public String getRegion() {
		return region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getUserLimit() {
		return userLimit;
	}

	public void setUserLimit(String userLimit) {
		this.userLimit = userLimit;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	


}
