package com.expertworks.lms.model;

import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.expertworks.lms.http.PartnerDTO;
import com.fasterxml.jackson.annotation.JsonIgnore;

@DynamoDBTable(tableName = "Partner")

public class Partner implements Comparable<Partner> {
	
	

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String partnerId;


	@DynamoDBRangeKey // CustomerBookmark Table referred.
	private String sk;

	@DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
	private Date createdDate;

	@DynamoDBAttribute
	private String name;
	
	@DynamoDBAttribute
	private String email;
	

	@DynamoDBAttribute
	private String groupId;

	@DynamoDBAttribute
	private String img;

	@DynamoDBAttribute
	private String mobile;
	
	@DynamoDBAttribute
	private String address;
	
	private List<String> groupIds;

	public int compareTo(Partner partner) {
		return sk.compareTo(partner.sk);

	}

	
	public PartnerDTO toPartnerDTO() {

		PartnerDTO partnerDTO = new PartnerDTO();
		partnerDTO.setPartnerId(this.partnerId);
		partnerDTO.setSk(this.sk);
		partnerDTO.setName(this.name);
		partnerDTO.setMobile(this. mobile);
		partnerDTO.setAddress(this.address);
		
	
		return partnerDTO;

	}


	public String getPartnerId() {
		return partnerId;
	}


	public void setPartnerId(String partnerId) {
		this.partnerId = partnerId;
	}


	public String getSk() {
		return sk;
	}


	public void setSk(String sk) {
		this.sk = sk;
	}


	public Date getCreatedDate() {
		return createdDate;
	}


	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public String getGroupId() {
		return groupId;
	}


	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}


	public String getImg() {
		return img;
	}


	public void setImg(String img) {
		this.img = img;
	}


	public List<String> getGroupIds() {
		return groupIds;
	}


	public void setGroupIds(List<String> groupIds) {
		this.groupIds = groupIds;
	}


	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	public String getMobile() {
		return mobile;
	}


	public void setMobile(String mobile) {
		this.mobile = mobile;
	}


	public String getAddress() {
		return address;
	}


	public void setAddress(String address) {
		this.address = address;
	}

	

}
